number1 = int(input("Enter the first number: "))
number2 = int(input("Enter the second number: "))
print("Thank You!")
print(f"{number1} + {number2} = {number1 + number2}")
print(f"{number1} - {number2} = {number1 - number2}")
print(f"{number1} * {number2} = {number1 * number2}")
print(f"{number1} / {number2} = {number1 / number2}")